rvm:
  - 1.8.7

before_script: "./spec/ci/before_script"

script: "./spec/ci/script"

env:
  - RADIANT_VERSION=master DB=postgres

notifications:
  recipients:
    - git@johnmuhl.com
  irc: "irc.freenode.org#radiantcms"
